=== ARTurleite6/ols/misc/ols.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"workspace_folders": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": { "type": "string" },
					"uri": { "type": "string" }
				}
			}
		},
		"collections": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": { "type": "string" },
					"path": { "type": "string" }
				}
			}
		},
		"completion_support_md": { "type": "boolean" },
		"hover_support_md": { "type": "boolean" },
		"signature_offset_support": { "type": "boolean" },
		"running": { "type": "boolean" },
		"verbose": {
			"type": "boolean",
			"description": "Logs warnings instead of just errors."
		},
		"enable_format": { "type": "boolean" },
		"enable_hover": {
			"type": "boolean",
			"description": "Enables hover feature"
		},
		"enable_document_symbols": {
			"type": "boolean",
			"description": "Turns on outline of all your global declarations in your document."
		},
		"enable_semantic_tokens": {
			"type": "boolean",
			"description": "Turns on syntax highlighting."
		},
		"enable_inlay_hints": { "type": "boolean" },
		"enable_procedure_context": { "type": "boolean" },
		"enable_snippets": {
			"type": "boolean",
			"description": "Turns on builtin snippets"
		},
		"enable_references": { "type": "boolean" },
		"enable_rename": { "type": "boolean" },
		"enable_label_details": { "type": "boolean" },
		"enable_std_references": { "type": "boolean" },
		"enable_import_fixer": { "type": "boolean" },
		"disable_parser_errors": { "type": "boolean" },
		"thread_count": { "type": "integer" },
		"file_log": { "type": "boolean" },
		"odin_command": {
			"type": "string",
			"description": "Allows you to specify your Odin location, instead of just relying on the environment path."
		},
		"checker_args": {
			"type": "string",
			"description": "Pass custom arguments to `odin check`."
		}
	},
	"required": []
}

=== ARTurleite6/ols/ols.json
{
    "collections": [
        {
            "name": "core",
            "path": "C:\\Users\\danie\\OneDrive\\Desktop\\Computer_Science\\Odin\\core"
        },
        {
            "name": "shared",
            "path": "src"
        }
    ],
    "enable_document_symbols": true,
    "enable_semantic_tokens": true,
    "enable_hover": true,
    "enable_snippets": true
}
